spring:
  application:
    name: devtest
  profiles:
    active: local
  data:
    redis:
        host: localhost
        port: 31110
        timeout: 5s

server:
  port: 5000
  error:
    include-message: always

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

rest-clients:
  product:
    base-url: http://localhost:3001
    auth-method: NONE
