spring:
  application:
    name: devtest
  profiles:
    active: local
  data:
    redis:
        host: localhost
        port: 31110
        timeout: 5s

server:
  port: 5000

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

rest-clients:
  product:
    base-url: http://localhost:3001
    connect-timeout: 5s
    read-timeout: 5s
    max-concurrent-calls: 50
    global-timeout: 6s

resilience4j:
  circuitbreaker:
    instances:
      product_external_api:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - com.inditex.devtest.exception.RemoteException
  retry:
    instances:
      product_external_api:
        maxAttempts: 3
        waitDuration: 250ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        exponentialMaxWaitDuration: 1s
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - com.inditex.devtest.exception.RemoteException
