resilience4j:
  circuitbreaker:
    instances:
      product_external_api:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - com.inditex.devtest.exception.RemoteException
        ignoreExceptions:
          - com.inditex.devtest.exception.AuthenticationExpiredException
          - com.inditex.devtest.exception.AccessDeniedException
          - com.inditex.devtest.exception.DomainException
  retry:
    instances:
      product_external_api:
        maxAttempts: 3
        waitDuration: 250ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        exponentialMaxWaitDuration: 1s
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - com.inditex.devtest.exception.RemoteException
        ignore-exceptions:
          - com.inditex.devtest.exception.AuthenticationExpiredException
          - com.inditex.devtest.exception.AccessDeniedException
          - com.inditex.devtest.exception.DomainException